app = 'qbot'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.24'

[env]
  PORT = '8080'
  CONFIG_FILE_PATH = "/data/config/config.json"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "litefs_data"
  destination = "/var/lib/litefs"

[[mounts]]
  source = "config"
  destination = "/data/config"
